server:
  port: ${PORT:8085}

spring:
  application:
    name: api-gateway

jwt:
  secret: ${JWT_SECRET:codeforge-ai-super-secret-jwt-key-256-bits-long-change-in-prod}

services:
  auth-url: ${AUTH_SERVICE_URL:http://localhost:8081}
  project-url: ${PROJECT_SERVICE_URL:http://localhost:8082}
  ingestion-url: ${INGESTION_SERVICE_URL:http://localhost:8083}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always